function run = T3_loop_the_loop_coulomb()

    cfg    = sim_config();
    params = ball_hoop_params();
    
    params.ball_track_friction_coeff = 0.5;


    [~, R_eff_o] = hoop_geometry('rolling_out', params);

    scn.id   = 'T3_loop_the_loop_coulomb';
    scn.name = 'T3 - Loop the loop (Coulomb-constrained, direct collocation + TVLQR)';
    scn.mode = 'rolling_out';
    scn.x0   = [R_eff_o; 0; 0; 0; 0; 0];
    
    scn.controller = struct( ...
        'type',    'TVLQR', ...
        'x0_red',  [0; 0; 0; 0], ...
        'xf_red',  [0; 0; -2*pi; 0], ...
        'K',       60, ...
        'Tf_min',  1.0, ...
        'Tf_max',  6.0, ...
        'u_max',   cfg.tau_max / params.total_inertia, ...    
        'Q',       diag([1e-3, 1, 100, 10]), ...
        'R',       0.1, ...
        'Qf',      diag([1e-3, 1, 100, 10]), ...
        'contact_margin',  0.20 * params.gravity, ...
        'enforce_no_slip', true);
        
    run = run_scenario(scn, params, cfg);
end
