function run = T4_flying_ball()

    params = ball_hoop_params();
    cfg    = sim_config();
    cfg.u_slip_max = 140;   
    
    [~, R_eff_o] = hoop_geometry('rolling_out', params);

    psi_des       = deg2rad(120);
    psi_dot_des   = sqrt(-params.gravity * cos(psi_des) / R_eff_o);   % 7.3183
    theta_dot_des = -8.00;
    Q_track = diag([1e-2, 1, 100, 1]);

    theta_hold_fit     = -25.2615;   % [rad] raw, on the turn the hoop is actually on
    theta_dot_hold_fit =  -4.8298;   % [rad/s]

    scn.id   = 'T4_flying_ball';
    scn.name = 'T4 - Flying ball: pump, release, fly through the gap, catch inside';
    scn.mode = 'rolling_out';
    scn.x0   = [R_eff_o; 0; 0; 0; 0; 0];
    scn.expected_mode_sequence = {'rolling_out', 'free_fall', 'rolling_in_inside'};

    scn.controller = struct( ...
        'type',                'T4', ...
        'x0_red',              [0; 0; 0; 0], ...
        'xf_red',              [pi; theta_dot_des; psi_des; psi_dot_des], ...
        'constrain_theta_f',   false, ...
        'psi_bounds',          [-1.5*pi, 1.02*pi], ...
        'theta_dot_max',       50, ...
        'psi_dot_max',         6*pi, ...
        'contact_margin',      0, ...   % the terminal state IS N = 0
        'constrain_midpoints', true, ...
        'enforce_no_slip',     true, ...
        'n_swings',            0, ...
        'K',                   60, ...
        'Tf_min',              0.5, ...
        'Tf_max',              5.0, ...
        'u_max',               cfg.tau_max / params.total_inertia, ...
        'Q',                   Q_track, ...
        'R',                   0.01, ...
        'Qf',                  Q_track, ...
        'theta_hold',          theta_hold_fit, ...
        'theta_dot_hold',      theta_dot_hold_fit, ...
        'kp_hold',             300, ...
        'kd_hold',             35, ...
        'slew_boundary',       1e9, ...
        'catch_mode',          'rolling_in_inside', ...
        'lqr_Q',               diag([1/(10*pi)^2, 1/5^2, 1/0.35^2, 1/1.5^2]), ...
        'lqr_R',               1e-3);

    run = run_scenario(scn, params, cfg);
end
